apiVersion: apps/v1
kind: Deployment
metadata:
  name: apirestmessage
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apirestmessage
  template:
    metadata:
      labels:
        app: apirestmessage
    spec:
      containers:
      - name: apirestmessage
        image: luizcssoares/apirestmessage:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
