apiVersion: apps/v1
kind: Deployment
metadata:
  name: apirestmessage
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apirestmessage
  template:
    metadata:
      labels:
        app: apirestmessage
    spec:
      containers:
      - name: apirestmessage
        image: luizcssoares/apirestmessage:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: apirestmessage
spec:
  selector:
    app: apirestmessage
  type: NodePort
  ports:
  - protocol: "TCP"
    port: 8080
    targetPort: 8080

