apiVersion: v1
kind: Service
metadata:
  name: apirestmessage
spec:
  selector:
    app: apirestmessage
  type: LoadBalancer
  ports:
  - protocol: "TCP"
    port: 8080
    targetPort: 8080
