name: CI

on:
  push:
    branches: [master]
    
jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permissions to mvnw
        run: chmod +x ./mvnw    

      - name: Build Spring Boot application
        run: |
          ./mvnw clean install     

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.USER_DOCKER_HUB }}
          password: ${{ secrets.PWD_DOCKER_HUB }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          context: .          
          push: true
          tags: |            
            luizcssoares/apirestmessage:latest
